
# STD Defines
#DDEFS += -DSTM32F10X_MD -DUSE_STDPERIPH_DRIVER -DHSE_VALUE=8000000

# use libraries, please add or remove when you use or remove it.
CPP_SRCS  += $(RADIOHEAD_DIR)/RHGenericDriver.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RH_CC110.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RH_E32.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_MRF89.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_NRF905.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_RF22.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_RF95.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_NRF24.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_RF24.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_NRF51.cpp
#CPP_SRCS  += $(RADIOHEAD_DIR)/RH_RF69.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHSPIDriver.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHGenericSPI.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHSoftwareSPI.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHHardwareSPI.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RH_Serial.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RH_TCP.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHCRC.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHEncryptedDriver.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHNRFSPIDriver.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHRouter.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHDatagram.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHMesh.cpp
CPP_SRCS  += $(RADIOHEAD_DIR)/RHReliableDatagram.cpp


# include directories
INCLUDE_DIRS += $(RADIOHEAD_DIR)


